import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { QRCodeSVG } from "qrcode.react";
import {
  Briefcase,
  Database,
  Download,
  ExternalLink,
  Globe,
  ShieldAlert,
  Sparkles,
  TrendingUp,
} from "lucide-react";
import { motion } from "framer-motion";
import { supabase } from "@/integrations/supabase/client";
import { lookupAutomation, lookupWage, wittgensteinProjections } from "@/utils/econometricData";
import { lookupEsco } from "@/utils/escoCrosswalk";

interface SkillRow {
  name: string;
  isco_code: string;
  automation_probability?: number;
}
interface JobRow {
  job_title: string;
  isco_code?: string;
  match_percent: number;
  local_wage: string;
  wage_source?: string | null;
  wage_year?: number | null;
}
interface AnalysisRow {
  id: string;
  share_id: string;
  ai_score: number;
  risk_level: string;
  skills: SkillRow[];
  jobs: JobRow[];
  signals: Record<string, unknown> | null;
  created_at: string;
}

export const Route = createFileRoute("/p/$shareId")({
  loader: async ({ params }) => {
    const { data, error } = await supabase
      .from("analyses")
      .select("id, share_id, ai_score, risk_level, skills, jobs, signals, created_at")
      .eq("share_id", params.shareId)
      .maybeSingle();
    if (error || !data) throw notFound();
    return data as unknown as AnalysisRow;
  },
  head: ({ params }) => ({
    meta: [
      { title: `Skills Profile · ${params.shareId} — Sawt-Net` },
      {
        name: "description",
        content:
          "Portable skills profile mapped to ISCO-08 and ESCO. Generated by Sawt-Net — voice-to-job platform for the unmapped economy.",
      },
      { property: "og:title", content: "Portable Skills Profile — Sawt-Net" },
      {
        property: "og:description",
        content:
          "ISCO-08 + ESCO standardized profile with AI-resilience score and local wage benchmarks.",
      },
    ],
  }),
  errorComponent: ({ error }) => (
    <FallbackShell title="Profile unavailable" body={error.message} />
  ),
  notFoundComponent: () => (
    <FallbackShell
      title="Profile not found"
      body="This share link is invalid or has been revoked."
    />
  ),
  component: PublicProfile,
});

function FallbackShell({ title, body }: { title: string; body: string }) {
  return (
    <div className="flex min-h-screen items-center justify-center bg-app-shell px-6">
      <div className="max-w-md rounded-2xl bg-card p-8 text-center shadow-[var(--shadow-floating)]">
        <h1 className="mb-2 text-xl font-bold">{title}</h1>
        <p className="mb-6 text-sm text-muted-foreground">{body}</p>
        <Link
          to="/"
          className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-2.5 text-sm font-bold text-primary-foreground"
        >
          Go to Sawt-Net
        </Link>
      </div>
    </div>
  );
}

function PublicProfile() {
  const analysis = Route.useLoaderData();
  const [copied, setCopied] = useState(false);

  // Decorate skills + jobs with the same client-side econometric lookups
  // used by the private results screen, plus ESCO mapping. This ensures
  // a publicly-shared profile carries Frey-Osborne, ILOSTAT and ESCO
  // context even if the original row was missing some signals.
  const enrichedSkills = useMemo(
    () =>
      (analysis.skills ?? []).map((s) => {
        const auto = lookupAutomation(s.isco_code);
        const esco = lookupEsco(s.isco_code);
        return {
          ...s,
          automation_probability: s.automation_probability ?? auto.probability,
          esco,
        };
      }),
    [analysis.skills],
  );
  const enrichedJobs = useMemo(
    () =>
      (analysis.jobs ?? []).map((j) => {
        const needsWage = !j.local_wage || j.local_wage === "—";
        const wage = lookupWage(j.isco_code ?? "");
        const esco = lookupEsco(j.isco_code ?? "");
        return {
          ...j,
          local_wage: needsWage ? wage.formatted : j.local_wage,
          wage_source: j.wage_source ?? wage.source,
          wage_year: j.wage_year ?? wage.year,
          esco,
        };
      }),
    [analysis.jobs],
  );

  const profileUrl =
    typeof window !== "undefined"
      ? `${window.location.origin}/p/${analysis.share_id}`
      : `https://sawt-net.app/p/${analysis.share_id}`;

  const portableProfile = useMemo(
    () => ({
      schema: "sawtnet.profile.v1",
      generated_at: new Date().toISOString(),
      profile_url: profileUrl,
      share_id: analysis.share_id,
      ai_resilience_score: analysis.ai_score,
      risk_level: analysis.risk_level,
      skills: enrichedSkills.map((s) => ({
        name: s.name,
        isco_code: s.isco_code,
        esco_code: s.esco.esco_code,
        esco_label: s.esco.esco_label_en,
        esco_uri: s.esco.esco_uri,
        automation_probability: s.automation_probability,
      })),
      opportunities: enrichedJobs.map((j) => ({
        job_title: j.job_title,
        isco_code: j.isco_code,
        esco_code: j.esco.esco_code,
        esco_label: j.esco.esco_label_en,
        esco_uri: j.esco.esco_uri,
        match_percent: j.match_percent,
        local_wage: j.local_wage,
        wage_source: j.wage_source,
        wage_year: j.wage_year,
      })),
      signals: analysis.signals ?? {},
      sources: {
        skills_taxonomy: "ISCO-08 (ILO) + ESCO v1.2 (European Commission)",
        automation: "Frey & Osborne (2017)",
        wages: "ILOSTAT — Mean nominal monthly earnings of employees by occupation",
        education_trend: wittgensteinProjections.source,
      },
    }),
    [analysis, enrichedSkills, enrichedJobs, profileUrl],
  );

  const downloadJson = () => {
    const blob = new Blob([JSON.stringify(portableProfile, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `sawtnet-profile-${analysis.share_id}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const copyLink = async () => {
    try {
      await navigator.clipboard.writeText(profileUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 1600);
    } catch {
      // ignore
    }
  };

  const riskTone =
    analysis.ai_score >= 70
      ? "bg-success/15 text-success"
      : analysis.ai_score >= 40
        ? "bg-warning/15 text-warning"
        : "bg-destructive/15 text-destructive";

  return (
    <div className="min-h-screen bg-app-shell">
      <header className="border-b border-border/40 bg-card/95 backdrop-blur-sm">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-5 py-4 sm:px-8">
          <Link to="/" className="flex items-center gap-2">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-primary to-[var(--primary-glow)] text-primary-foreground">
              <Sparkles className="h-4 w-4" />
            </div>
            <div>
              <h1 className="text-sm font-extrabold tracking-tight">Sawt-Net</h1>
              <p className="text-[10px] font-medium text-muted-foreground">
                Portable skills profile
              </p>
            </div>
          </Link>
          <span className="rounded-full bg-[color:var(--primary-soft)] px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-[color:var(--primary-deep)]">
            Public
          </span>
        </div>
      </header>

      <main className="mx-auto max-w-3xl space-y-4 px-4 py-6 sm:px-8">
        {/* Hero — share controls */}
        <motion.section
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          className="rounded-2xl bg-card p-5 shadow-[var(--shadow-floating)]"
        >
          <div className="flex flex-col gap-5 sm:flex-row sm:items-center">
            <div className="shrink-0 self-center rounded-xl bg-white p-3 shadow-[var(--shadow-card)]">
              <QRCodeSVG value={profileUrl} size={112} level="M" includeMargin={false} />
            </div>
            <div className="min-w-0 flex-1">
              <div className="mb-1 inline-flex items-center gap-1.5 rounded-full bg-success/15 px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-wider text-success">
                <Database className="h-2.5 w-2.5" />
                ISCO-08 · ESCO · ILOSTAT
              </div>
              <h2 className="text-lg font-extrabold tracking-tight">
                Portable Skills Profile
              </h2>
              <p className="mt-0.5 break-all text-xs text-muted-foreground">
                {profileUrl}
              </p>
              <div className="mt-3 flex flex-wrap gap-2">
                <button
                  type="button"
                  onClick={copyLink}
                  className="inline-flex items-center gap-1.5 rounded-full bg-muted px-3 py-1.5 text-xs font-bold transition hover:bg-accent"
                >
                  <Globe className="h-3.5 w-3.5" />
                  {copied ? "Link copied" : "Copy link"}
                </button>
                <button
                  type="button"
                  onClick={downloadJson}
                  className="inline-flex items-center gap-1.5 rounded-full bg-gradient-to-r from-primary to-[var(--primary-glow)] px-3 py-1.5 text-xs font-bold text-primary-foreground shadow-[var(--shadow-card)]"
                >
                  <Download className="h-3.5 w-3.5" />
                  Download JSON
                </button>
              </div>
            </div>
          </div>
        </motion.section>

        {/* AI Resilience */}
        <Section icon={<ShieldAlert className="h-4 w-4" />} title="AI-Resilience Score">
          <div className="mb-3 flex items-end justify-between gap-3">
            <div>
              <span className="text-5xl font-extrabold tracking-tight">
                {analysis.ai_score}
              </span>
              <span className="ml-1 text-xl font-bold text-muted-foreground">/100</span>
            </div>
            <span className={`rounded-full px-3 py-1 text-xs font-bold ${riskTone}`}>
              {analysis.risk_level}
            </span>
          </div>
          <div className="h-2.5 w-full overflow-hidden rounded-full bg-muted">
            <div
              className="h-full rounded-full bg-gradient-to-r from-primary to-[var(--primary-glow)]"
              style={{ width: `${analysis.ai_score}%` }}
            />
          </div>
          <p className="mt-3 flex items-center gap-1.5 text-[11px] text-muted-foreground">
            <Database className="h-3 w-3" />
            <span className="font-semibold uppercase tracking-wide">Source:</span>
            <span>Frey &amp; Osborne (2017)</span>
          </p>
        </Section>

        {/* Skills with ESCO chips */}
        <Section
          icon={<TrendingUp className="h-4 w-4" />}
          title="Skills (ISCO-08 · ESCO)"
          subtitle="Each skill carries its standardized European code so this profile is portable across borders."
        >
          <div className="flex flex-wrap gap-2">
            {enrichedSkills.map((s, i) => {
              const pct =
                typeof s.automation_probability === "number"
                  ? Math.round(s.automation_probability * 100)
                  : null;
              return (
                <div
                  key={`${s.isco_code}-${i}`}
                  className="rounded-xl bg-[color:var(--primary-soft)] p-3 text-[color:var(--primary-deep)] shadow-[var(--shadow-card)]"
                >
                  <div className="text-sm font-bold">{s.name}</div>
                  <div className="mt-1.5 flex flex-wrap items-center gap-1.5 text-[10px] font-bold">
                    <span className="rounded-full bg-white/70 px-2 py-0.5">
                      ISCO {s.isco_code}
                    </span>
                    <a
                      href={s.esco.esco_uri}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-1 rounded-full bg-white/70 px-2 py-0.5 hover:bg-white"
                      title={s.esco.esco_label_en}
                    >
                      ESCO {s.esco.esco_code}
                      <ExternalLink className="h-2.5 w-2.5" />
                    </a>
                    {pct !== null && (
                      <span className="rounded-full bg-white/70 px-2 py-0.5">
                        🤖 {pct}%
                      </span>
                    )}
                  </div>
                  <div className="mt-1 text-[10px] italic text-[color:var(--primary-deep)]/70">
                    {s.esco.esco_label_en}
                  </div>
                </div>
              );
            })}
          </div>
        </Section>

        {/* Opportunities */}
        <Section
          icon={<Briefcase className="h-4 w-4" />}
          title="Matched Opportunities"
          subtitle={`${enrichedJobs.length} reachable roles`}
        >
          <div className="space-y-3">
            {enrichedJobs.map((j, i) => (
              <div
                key={`${j.job_title}-${i}`}
                className="rounded-2xl bg-card p-4 shadow-[var(--shadow-card)] ring-1 ring-border/60"
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="min-w-0">
                    <h3 className="text-[15px] font-bold leading-tight">{j.job_title}</h3>
                    <div className="mt-1 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-muted-foreground">
                      <span className="font-semibold text-foreground/80">
                        {j.local_wage}
                      </span>
                      {j.isco_code && (
                        <span className="rounded-full bg-muted px-2 py-0.5 text-[10px] font-bold">
                          ISCO {j.isco_code}
                        </span>
                      )}
                      <a
                        href={j.esco.esco_uri}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 rounded-full bg-muted px-2 py-0.5 text-[10px] font-bold hover:bg-accent"
                      >
                        ESCO {j.esco.esco_code}
                        <ExternalLink className="h-2.5 w-2.5" />
                      </a>
                    </div>
                  </div>
                  <span className="shrink-0 rounded-full bg-success/15 px-2.5 py-0.5 text-xs font-bold text-success">
                    {j.match_percent}%
                  </span>
                </div>
              </div>
            ))}
          </div>
          <p className="mt-3 flex items-center gap-1.5 text-[11px] text-muted-foreground">
            <Database className="h-3 w-3" />
            <span className="font-semibold uppercase tracking-wide">Source:</span>
            <span>ILOSTAT 2023, National Median</span>
          </p>
        </Section>

        <p className="px-2 pb-8 pt-2 text-center text-[11px] leading-relaxed text-muted-foreground">
          Generated by Sawt-Net. Wages are national medians; automation scores are
          based on Frey-Osborne (US labour market) and may differ in informal LMIC
          contexts. ESCO mapping uses ESCO v1.2.
        </p>
      </main>
    </div>
  );
}

function Section({
  icon,
  title,
  subtitle,
  children,
}: {
  icon: React.ReactNode;
  title: string;
  subtitle?: string;
  children: React.ReactNode;
}) {
  return (
    <section className="rounded-2xl bg-card p-5 shadow-[var(--shadow-floating)]">
      <div className="mb-1 flex items-center gap-2 text-primary">
        <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-[color:var(--primary-soft)] text-[color:var(--primary-deep)]">
          {icon}
        </span>
        <h2 className="text-base font-extrabold tracking-tight text-foreground">
          {title}
        </h2>
      </div>
      {subtitle && (
        <p className="mb-4 text-xs font-medium text-muted-foreground">{subtitle}</p>
      )}
      {children}
    </section>
  );
}
